<a href="https://colab.research.google.com/github/kasi1989/Python_NLP/blob/master/CHALLENGE5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Challenge 5** : Assume you are looking to build a model to predict if the text you are seeing is an issue or informational message. For e.g. job completed is an informational message whereas job abended is an issue. The objective is to predict the issue.

The task is multi fold

1. Generate the label for each data point to see if its informational or an issue
2. Build a count based matrix for each issue which reflects the number of occurrence of each word in the text along with the label
3. You can choose to restrict to a certain number of words based on your analysis 
4. You can choose to remove the STOPWORDS from each text 
5. The count based matrix that you build for the entire data set should be in a format such that it can be given as an input to any of the algorithm for training and testing.

#Import the libraries required

In [ ]:
#Import the libraries required
import numpy as np
import pandas as pd
import nltk
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

#Read Input file & Label creation

In [ ]:
#Read Input file
data = pd.read_csv('ticket_Data.csv')
data.shape
type(data)

#Remove missing values
data = data.dropna()
# Removing the column TicketId. 
data = data.drop("TicketId", axis=1) 
#Lower text 
data['Description'] = data['Description'].str.lower() 
#searching values in description
search_values = ['completed','re-started','success','resolve','re-run','cleared']
# creating and passsing series to new column 
data["Indexes"]= data["Description"].str.contains('|'.join(search_values )) 
data['Indexes'].groupby(data['Indexes']).count() #Count of Indexes records
# creating label column 
data['label'] = np.where(data['Indexes']==False, 'Issue', 'Information')
data['label'].groupby(data['label']).count() #Count of issue vs Information records




label
Information    4745
Issue          1700
Name: label, dtype: int64

# Data Preprocessing

In [ ]:
# create selected column a list to enable further clean-up
data_list = list(data['Description'])
type(data_list)
#custom function
def tok(text):
  tokens = word_tokenize(text)
  return tokens
import regex as re
#Custom Preprocessing
def custom_preprocessor(text):
  #lowering the text case
  text = text.lower() 
  # remove special chars
  text = re.sub("\\W"," ",text)
  return text

cv2 = CountVectorizer(data_list,stop_words='english',min_df=2,tokenizer=tok,preprocessor=custom_preprocessor,lowercase=True,  token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 4), analyzer='word')

#Lets test cv2 on our doc
cv2_doc = cv2.fit_transform(data_list)
cv2_doc


<6445x5457 sparse matrix of type '<class 'numpy.int64'>'
	with 134818 stored elements in Compressed Sparse Row format>

In [ ]:
#@title Default title text
print(cv2.vocabulary_)

{'job': 2606, 'run': 4195, 'job run': 3023, 'failed': 1388, 'row': 4184, 'count': 807, 'mismatch': 3555, 'source': 4483, 'file': 1696, 'ods': 3665, 'table': 4856, 'requested': 4039, 'team': 4997, 'place': 3749, 'files': 1865, 'completed': 582, 'placing': 3762, 'path': 3714, 'job failed': 2772, 'failed row': 1568, 'row count': 4185, 'count mismatch': 814, 'mismatch source': 3561, 'source file': 4521, 'file ods': 1796, 'ods table': 3666, 'table requested': 4871, 'requested source': 4043, 'source team': 4617, 'team place': 5024, 'place source': 3753, 'source files': 4578, 'files job': 1872, 'job completed': 2687, 'completed placing': 609, 'placing source': 3763, 'file source': 1824, 'source path': 4602, 'job failed row': 2803, 'failed row count': 1569, 'row count mismatch': 4189, 'count mismatch source': 819, 'mismatch source file': 3562, 'source file ods': 4559, 'file ods table': 1797, 'ods table requested': 3667, 'table requested source': 4872, 'requested source team': 4044, 'source tea

In [ ]:
# summarize encoded vector
print(cv2_doc.shape)
print(type(cv2_doc))
print(cv2_doc.toarray())


(6445, 5457)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
